openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /inference:
    get:
      description: "Inference LLaMA model"
      responses:
        "200":
          description: "OK"
          content:
            multipart/form-data:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
components:
  schemas:
